version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: mta-atsea
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - backend
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: mta-atsea-db
    networks:
      - backend
networks:
  backend: