version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: mta-atsea
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3m
      retries: 10
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: mta-atsea-db
    networks:
      - backend
networks:
  backend: